### ISSUE TITLE
react-native-linear-gradient Required module not found

### ISSUE THREAD

**Issue by naineshg** [react-native-community/react-native-linear-gradient#110]
I'm getting `react-native-linear-gradient Required module not found` from Flow in my React-Native project. Any ideas why?

**Comment by spencerwiggins** [comment]
I'm assuming your using `import LinearGradient from 'react-native-linear-gradient';`?  I believe the issue here is the LinearGradient directory has an android file `index.android.js` and `index.ios.js` and the import doesn't know which to choose from.

One way to resolve this is to create a LinearGradient directory somewhere in your project.  Create an index.js file within that directory, then add the following:

`// @flow

import { Platform } from 'react-native';
import LinearGradientAndroid from 'react-native-linear-gradient/index.ios.js';
import LinearGradientIos from 'react-native-linear-gradient/index.android.js';

const LinearGradient = Platform.OS === 'ios' ? LinearGradientIos : LinearGradientAndroid;

export default LinearGradient;
`
Then in your component where you want to use the gradient component, `import LinearGradient from '../LinearGradient';`

That should resolve it.

**Comment by NaineshG** [comment]
Now I'm getting this.

<img width="864" alt="screen shot 2016-09-14 at 1 59 37 pm" src="https://cloud.githubusercontent.com/assets/3132196/18523754/a3dbcf34-7a83-11e6-858a-2b4bc279cdda.png">

**Comment by spencerwiggins** [comment]
Hmm, try manually installing the dependencies https://github.com/react-native-community/react-native-linear-gradient#add-it-to-your-project and make sure the package is installed correctly within node_modules.

**Comment by dsernst** [comment]
I'm seeing a similar error from `eslint`. 

<img width="662" alt="screen shot 2016-09-27 at 11 43 14 pm" src="https://cloud.githubusercontent.com/assets/6340841/18903126/32665804-850c-11e6-8178-c6887903ea50.png">

Although it's working fine in the iOS simulator.

**Comment by mcrowe** [comment]
I'm getting the same issue. It seems like Flow issue, rather than one for this library to fix. Flow doesn't seem to cope well with `.ios.js` and `.android.js` extensions.

You can tell Flow to ignore this line by following https://medium.com/@wietsevenema/ignore-a-flowtype-error-on-a-specific-line-14cdfa70a739#.46pvvybab

**Comment by danielsukmana** [comment]
I have had this issue before. The problem is that Flow doesn't recognize files with the extensions `.ios.js` and `.android.js`. The solution I use is to add these lines to the `.flowconfig` file (you can change it according to your needs).
```
module.file_ext=.ios.js
module.file_ext=.android.js
module.file_ext=.js
module.file_ext=.json
```

**Comment by mcrowe** [comment]
The suggestion by @danielsukmana solved the issue for me. To be clear, these lines should go under the `[options]` section of your `.flowconfig`

I have no idea why ReactNative wouldn't include these lines in their default `.flowconfig`. It does seem that the issue is a ReactNative one, and not this package. I'd recommend closing unless @naineshg is unable to get fix the issue with the above suggestion.

**Comment by dsernst** [comment]
Want to point out this [issue also affects `eslint`](https://github.com/react-native-community/react-native-linear-gradient/issues/110#issuecomment-250085066), not just Flow. So the `.flowconfig` change isn't applicable.

**Comment by femiveys** [comment]
Any idea when this will be fixed? There needs to be an index.js file for eslint to work properly.

**Comment by naineshg** [comment]
@mcrowe Sorry for replying late. That suggestion does solved the problem. Thanks!

**Comment by neiker** [comment]
This breaks eslint and also mocha can't import this module.

why don't add a index.js? or change index in package.json?

**Comment by filipsuk** [comment]
@danielsukmana you missed .jsx extension. Complete list:
```
module.file_ext=.ios.js
module.file_ext=.android.js
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
```

**Comment by GantMan** [comment]
Anyone here know the TypeScript way to solve this one?

**Comment by Jpunt** [comment]
These issues were solved by using `module.file_ext`, but are back after upgrading to the latest version of all deps. Does anyone else have the same problem?

**Comment by GantMan** [comment]
PR #174 saves the day.

**Comment by PaitoAnderson** [comment]
@GantMan: I created a PR for TypeScript support as well. #222
