### ISSUE TITLE
Finder Gradient Border overlaying transparent background

### ISSUE THREAD

**Issue by larryranches** [react-native-community/react-native-linear-gradient#114]
Is it possibly to have the gradient border to be finer with a gradient going from transparent ( 'rgba(0,0,0,0)' to black (#000)?

When the above gradient is overlaying a transparent background you can see a "white/brighter" line where the gradient end. See picture below.

![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/191961/19332796/65eaa8da-90a4-11e6-80b6-f86fed2f2399.jpg)

**Comment by nickhudkins** [comment]
Hey @larryranches you'll want to adjust your positions so that it is fully transparent before the end of the view that has the gradient within it. That will result in a more subtle falloff.

specifically:

`start={[0.0, 0.0]} end={[0.0, 0.75]}` may get you there. You'll want to adjust the Y value of `end`
