### ISSUE TITLE
Memory leak with react .39

### ISSUE THREAD

**Issue by tonyneel923** [react-native-community/react-native-linear-gradient#130]
If I leave my app open on a page that this component is used on android I get an app crash. Has anyone else experienced this issue?

**Comment by tonyneel923** [comment]
It appears to happen on android if you have more than one gradient on the page. If you delete pixel radii it works so I think this is what is causing the memory leak.

**Comment by victor-axelsson** [comment]
I also get this on iOS. It appears to be of the same reason. If you have more than one gradient. These are my versions: 

```
  "dependencies": {
    "firebase": "4.1.3",
    "instabug-reactnative": "1.2.0",
    "libphonenumber-js": "0.4.19",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.1",
    "react-native-communications": "2.2.1",
    "react-native-contacts": "0.8.2",
    "react-native-google-analytics-bridge": "5.1.0",
    "react-native-i18n": "2.0.2",
    "react-native-keyboard-aware-scroll-view": "0.2.9",
    "react-native-linear-gradient": "2.0.0",
    "react-navigation": "1.0.0-beta.11",
    "react-redux": "5.0.5",
    "redux": "3.7.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  }
```
Tested on real device, iPhone 7 plus, and simulator same version. 

Solutions: I just removed it and don't know why this happens. Maybe it's a race conditions when sharing resources since it seems to happen when you include more than one on the same page.

**Comment by sibelius** [comment]
is this still a problem?

reopen if yes
