### ISSUE TITLE
Tried to register two views with same name BVLinear gradient

### ISSUE THREAD

**Issue by shohailahm** [react-native-community/react-native-linear-gradient#292]
running  through git repo from package.json
linked manually
RN version:0.52
![screenshot_2018-05-28-17-15-59-162_com voise](https://user-images.githubusercontent.com/28625064/40613148-f586fbfa-629a-11e8-833d-65db75438f4d.png)

**Comment by sibelius** [comment]
this happens because you installed 2 versions of react-native-linear-gradient

check your node_modules

you should have only one

one of your deps have rn-linear-gradient as a dep

**Comment by shohailahm** [comment]
no..i checked several times there is only 1..

**Comment by shohailahm** [comment]
shoutem ui has one..so should i delete that folder?
or is there something else that i should do?

**Comment by sibelius** [comment]
open an issue there, they should have this package as a peer dep

**Comment by pistonsky** [comment]
I solved this by just running `yarn add react-native-linear-gradient` in my repo. I already had that dependency, but I used earlier version, specified with exact version number in my package.json. Another lib was also using react-native-linear-gradient, but newer version, that's why it all ended up having 2 versions of the same lib.

**Comment by jamesxabregas** [comment]
For the record I was getting this same issue, but for me it was because my import was not per the documentation. 

I had:
`import {LinearGradient} from "react-native-linear-gradient";`

When it needs to be as so (without curly braces):
`import LinearGradient from "react-native-linear-gradient";`

I also have react-native-svg installed which has its own component called LinearGradient, but I'm not sure if that was a red herring.

**Comment by hellolex** [comment]
How can I solve this problem? I also encountered this problem recently. A component installed also has this dependency, but I need it
