### ISSUE TITLE
Linear Gradient does not working in react-native latest version for only Android

### ISSUE THREAD

**Issue by harikanammi** [react-native-community/react-native-linear-gradient#310]
Hi, i am running sample application. In my case linear gradient is not working properly in Android. In iOS its working fine for me...Please give me any suggestion.

> "react-native": "0.55.4",
> "react-native-linear-gradient": "^2.4.0"

**Comment by CrazyPython** [comment]
@harikanammi Can you give more details about *how* it's not working?

**Comment by nguyenvanphuc2203** [comment]
hey i get same issue :D please help me

**Comment by CrazyPython** [comment]
Provide a reproducible example.

These commands run the example project included with the repository on React Native 0.56.0-rc.4. If you can reproduce the issue on 0.56.0-rc.4, let the maintainers know.
```
git clone https://github.com/crazypython/react-native-linear-gradient.git
cd react-native-linear-gradient/Examples/AnimatedGradient
yarn
react-native run-android
```

If you can't reproduce the issue with those commands, you can do one of the following:
* Modify package.json so that the dependencies are corrected to use your React Native version (note that this means modifying babel, react, react native, and the other peerDependencies of react native)
* Upgrade to React Native 0.56.0-rc.4 and `yarn upgrade react-native-linear-gradient@react-native-community/react-native-linear-gradient` see if it fixes the issue (I had to `react-native-git-upgrade 0.56.0-rc.4`, then modify package.json to use `0.56.0-rc.4`, then fix peerDependency warnings to get this to work)
* Look for an error in your code.

Don't forget to recompile after updating RNLG.

**Comment by radex** [comment]
Hey! I'm closing this since this is a stale issue. If you believe it's still relevant to fix, post a comment and I'll reopen.

**Comment by thanh90** [comment]
i upgraded expo to 34, eveything seems working well in debug mode, but in release mode, nothing works

**Comment by thanh90** [comment]
try to modify proguard helping me https://github.com/unimodules/react-native-unimodules/issues/53
