### ISSUE TITLE
iOS issue: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by tiludropdancer** [react-native-community/react-native-linear-gradient#434]
I'm trying to use LinearGradient from 'react-native-linear-gradient'.

I have imported the library using npm install react-native-linear-gradient --save. It has been automatically linked and "react-native-linear-gradient": "^2.5.6" has been added to package.json.

I am using IntelliJ IDEA to build and run the app using react-native-cli run-ios.

However I run into this issue:
<img width="339" alt="Screen Shot 2019-08-17 at 3 44 54 PM" src="https://user-images.githubusercontent.com/8205616/63218097-0805ae80-c108-11e9-8a06-f54a8dcd06c8.png">

Does anyone know how to fix this?

**Comment by cccccccccccccccccnrd** [comment]
having the same issue

**Comment by fabianperez** [comment]
@tiludropdancer Did you `pod install`?

**Comment by tiludropdancer** [comment]
I am no longer using this component or library for that matter, but I did run into this issue for other library imports as well. My solution was to upgrade the version of react-native-cli that I was running, then do these steps:

```
npm install some-library --save
cd ios
pod install
cd ..
react-native link
```

Keep in mind some libraries cannot be autolinked and will require disabling autolinking for that dependency in ```react-native.config.js``` like so:

```
module.exports = {
  dependencies: {
    'some-unsupported-package': {
      platforms: {
        android: null,
        ios: null
      },
    },
  },
};
```

then run this to link manually
```react-native link name-of-library```

**Comment by PCMACHero** [comment]
I had to do quite a few steps that the readme doesnt mention, presumably because they are implied for people that have used React Native for a while? I had to to:

pod install (in the ios folder)
cd .. and then react-native link
restart (command C on the metro bundler window, and re-run react-native run-ios)

**Comment by RishavKumar-3796** [comment]
@shohailahm Please don't referece to un necesary files. In the top it's written iOS issue and you're referencing to android. Please understand the difference.

**Comment by fsepulveda** [comment]
This [comment](https://github.com/react-native-community/react-native-linear-gradient/issues/422#issuecomment-546627723) fix the same problem terminate dev-server and run 
yarn start --reset-cache

**Comment by StanislavMaslow** [comment]
As i understood this is happening because of react-native version > 0.60 do not need linking (but i did "react-native link react-native-linear-gradient" during of the installation process). I run "react-native unlink react-native-linear-gradient" --> rebuild project in Xcode and after this gradient started to work.

**Comment by prashanthpanthu** [comment]
I am not resolving this issue please help me 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-01 at 13 14 06](https://user-images.githubusercontent.com/70694621/94781842-066c7800-03e8-11eb-9cce-b4191902e17f.png)
